Fixes zombie movements #3
4981-AITeam/4981_Linux_Game pull request #17
Opened 2017-03-29 04:47 UTC by fredyang001

2017-03-29 18:52 UTC, RobertArendac requested changes
Some styling changes required.

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +            || ch.detectMovementCollision(ch.getQuadTreeEntities(ch.quadtreeTurret, this), this));*/
Instead of commenting out unused code, you could just get rid of it entirely

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +    float oldY = getY();
Make things const when you can

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +    }
You made a method to check if the zombie hit something, why not use that here?

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +    }
Same as above, why not use your method?

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +    float dist = sqrt((curX - oldX)*(curX - oldX) + (curY - oldY)*(curY - oldY));
Make const

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +}
Is this function necessary if it's just going to call essentially the same function?

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +    static priority_queue<Node> pq[2];
Why change this from what was there before?

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +    int yNodeDest = static_cast<int> (dest.first + TILE_OFFSET) / TILE_SIZE - 1;
Why remove the const for each variable?

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +    static Node childNode;
Do these need to be static?

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +    curNode = Node(xNodeStart, yNodeStart, 0, 0);
Why use copying when you could've used the constructor when declaring it?

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +                       pq[index].top().getLevel(), pq[index].top().getPriority());
Why can't this be `curNode = pq[index].top()`?

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +                path = c + path;
Why do you need the `c` variable if you only use it here?

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +            }
Why change this?  They both do the same thing but `pq[index] = priority_queue<Node>()` was a quicker and cleaner solution.

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +                childNode = Node(newRow, newCol, curNode.getLevel(), curNode.getPriority());
Why change this?

2017-03-29 18:52 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +                        pq[1-index].push(pq[index].top());
Why take out the spacing?

2017-03-29 23:36 UTC, fredyang001 commented
made changes per feedback

2017-03-30 16:51 UTC, RobertArendac requested changes
Just one small change I'd like you to make

2017-03-30 16:51 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +        } else if (collisionObjId > 2) { // marine, turret, or barricade
Base is something the zombie is going to attack as well, you can just change this thing to:
```
if (collisionObjId > 2)
    setState(ZombieState::ZOMBIE_ATTACK);

2017-04-04 18:09 UTC, merged